# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_arrowextendr_wrappers", use_symbols = TRUE, package_name = "arrowextendr")

#' @docType package
#' @usage NULL
#' @useDynLib arrowextendr, .registration = TRUE
NULL

#' @export
test_i32 <- function() .Call(wrap__test_i32)

#' @export
test_f64 <- function() .Call(wrap__test_f64)

#' @export
test_field <- function() .Call(wrap__test_field)

#' @export
test_record_batch <- function() .Call(wrap__test_record_batch)

#' @export
test_schema <- function() .Call(wrap__test_schema)

#' @export
test_datatype <- function() .Call(wrap__test_datatype)

#' @export
test_from_field <- function(field) invisible(.Call(wrap__test_from_field, field))

#' @export
test_from_datatype <- function(field) invisible(.Call(wrap__test_from_datatype, field))

#' @export
test_from_schema <- function(field) invisible(.Call(wrap__test_from_schema, field))

#' @export
test_from_array <- function(field) invisible(.Call(wrap__test_from_array, field))

#' @export
test_from_recordbatch <- function(rb) invisible(.Call(wrap__test_from_recordbatch, rb))

#' @export
test_from_array_steam_reader <- function(rb) invisible(.Call(wrap__test_from_array_steam_reader, rb))

#' @export
process_stream <- function(stream) .Call(wrap__process_stream, stream)


# nolint end
