[package]
name = 'arrow_extendr'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ["staticlib", "lib"]
name = 'arrow_extendr'

[dependencies]
arrow = { version = "49.0.0", features = ["ffi"] }
extendr-api = '>=0.6.0'
