# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_arrowextendr_wrappers", use_symbols = TRUE, package_name = "arrowextendr")

#' @docType package
#' @usage NULL
#' @useDynLib arrowextendr, .registration = TRUE
NULL

#' @export
find_narrow <- function() invisible(.Call(wrap__find_narrow))

#' @export
export_array <- function() .Call(wrap__export_array)

#' @export
toarrow_trait <- function() .Call(wrap__toarrow_trait)


# nolint end
