# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_arrowextendr_wrappers", use_symbols = TRUE, package_name = "arrowextendr")

#' @docType package
#' @usage NULL
#' @useDynLib arrowextendr, .registration = TRUE
NULL

#' @export
find_narrow <- function() invisible(.Call(wrap__find_narrow))

#' @export
test_i32 <- function() .Call(wrap__test_i32)

#' @export
test_f64 <- function() .Call(wrap__test_f64)

#' @export
test_field <- function() .Call(wrap__test_field)

#' @export
test_record_batch <- function() .Call(wrap__test_record_batch)


# nolint end
